### ISSUE TITLE
Tarea infografia matematicas discretas

### ISSUE THREAD

**Issue by chelui5** [SistemasTecTlaxiaco/infografia-chelui5#1]
[infografia- sistema numerico.pdf](https://github.com/user-attachments/files/16735539/infografia-.sistema.numerico.pdf)

**Comment by Johnc-byte** [comment]
redacción y ortografía : 14/13
exposición de ideas centrales : 16/16
organización de ideas centrales : 14/14
uso de imágenes y colores : 14/14
presentación visual : 14/14
referencias : 11/14
presentación : 14/14
calificación final : 18/20

**Comment by josealfredo79** [comment]
bien hecho y revisado
